---
# vars file for vnf_automation
MYSQL_USER:     controlDb
MYSQL_PASSWD:   admin
MYSQL_DB:       cms
CONTROLLER :    IP
DB_UPGRADE_SCRIPT_PATH:  http://IP:PORT/file.tar.gz
CMS_ACT_USER: "root"
CMS_STB_USER: "root"
CONTROLLER_SYSUSER: "root"
CONTROLLER_SYSPASS: "admin"
KEYSTONE_SOURCE_PATH : /root/keystonerc_vnfm
HOME_DIR : /home/
CMS_ACTIVE_YAML_NAME : CMS_Multiple_Int_Active.yaml
CMS_ACTIVE_ENV_NAME : CMS_Multiple_Int_Active.env
CMS_ACTIVE_STACK_DELETE : cms_1_P7_1_14_2
CMS_STANDBY_YAML_NAME : CMS_Multiple_Int_Standby.yaml
CMS_STANDBY_ENV_NAME : CMS_Multiple_Int_Standby.env
CMS_STANDBY_STACK_DELETE : cms_2_P7_1_14_2
CMS_IMAGE_DELETE_NAME : CMSP_7_1_14_2-j1899
CMS_IMAGE_CREATION_NAME : CMSR_7_1_15_0-j2034
CMS_IMAGE_LINK: http://IP:PORT/file.qcow2.txz

CMS_RETRIES: 10
CMS_DELAY: 30

CMS_ACT_IP: IP
CMS_STB_IP: IP
CMS_URL: "https://IP:18080"
CMS_IP_SYSUSER: "root"
CMS_IP_SYSPASS: "admin"

